# Generated by Django 3.2.15 on 2022-10-24 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=149)),
                ('description', models.TextField(unique=True)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('points_free', models.IntegerField(blank=True, default=0)),
                ('user_account_funds', models.CharField(blank=True, max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votation_user', to='votaciones.voting')),
            ],
        ),
    ]
