# Generated by Django 3.2.15 on 2022-10-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
