# Generated by Django 3.2.15 on 2022-10-25 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_vote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='end_votation',
            field=models.DateField(default=datetime.datetime(2022, 10, 25, 5, 9, 51, 508667, tzinfo=utc)),
        ),
    ]
