# Generated by Django 3.2.15 on 2022-10-25 05:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votaciones', '0006_auto_20221025_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user_a',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='end_votation',
            field=models.DateField(default=datetime.datetime(2022, 10, 25, 5, 14, 30, 572667, tzinfo=utc)),
        ),
    ]
